"""Resolves place names against a district CSV held in memory.

The file is `src/dss/config/districts.csv` by default, generated by
`scripts/generate_district_csv.py` from an LGD snapshot. 784 rows, so the whole
index is built once at startup and never re-read — a lookup is a dict hit, not a
file read, because it sits on the path of every located turn.

Named `csv_lookup` rather than `csv` so the module does not shadow the stdlib
`csv` it imports.
"""

from __future__ import annotations

import csv
from pathlib import Path

from dss.core.shared.models import Geometry
from dss.ports.area_lookup import AreaMatch


class DistrictCsvUnusable(RuntimeError):
    """The district index could not be built, so no turn can resolve a place.

    Raised rather than logged: the file is checked in, so a missing or empty one
    means a broken build or a misconfigured path. Booting anyway would serve
    turns that have silently lost every spatial filter.
    """


def _key(name: str) -> str:
    """Case- and whitespace-insensitive. "  pune " and "Pune" are one key."""

    return " ".join(name.split()).lower()


class CsvAreaLookup:
    """An `AreaLookup` over a pre-built index. Use `load` to read a file."""

    def __init__(self, by_name: dict[str, tuple[AreaMatch, ...]]) -> None:
        self._by_name = by_name

    @classmethod
    def load(cls, path: Path) -> CsvAreaLookup:
        """Read the file once and hold the index. Raises `DistrictCsvUnusable`
        if it cannot be read or carries no districts."""

        by_name: dict[str, list[AreaMatch]] = {}
        try:
            with path.open(newline="", encoding="utf-8") as handle:
                for row in csv.DictReader(handle):
                    match = AreaMatch(
                        name=row["area_name"],
                        region=row["region"],
                        # GeoJSON order: longitude first.
                        geometry=Geometry(
                            coordinates=[
                                float(row["longitude"]),
                                float(row["latitude"]),
                            ]
                        ),
                    )
                    by_name.setdefault(_key(match.name), []).append(match)
        # KeyError and ValueError cover a renamed column and an unparseable
        # coordinate — both leave a partial index that would resolve some names
        # and silently miss others.
        except (OSError, KeyError, ValueError) as cause:
            raise DistrictCsvUnusable(
                f"could not read the district index at {path}: {cause}. "
                f"Regenerate it with: uv run python scripts/generate_district_csv.py "
                f"--source <network-adapter>/tools/area-lookups/data/areas/"
                f"<snapshot>/areas.csv"
            ) from cause

        if not by_name:
            raise DistrictCsvUnusable(
                f"the district index at {path} carries no districts, so no turn "
                f"could resolve a place name. Regenerate it with: uv run python "
                f"scripts/generate_district_csv.py --source <network-adapter>"
                f"/tools/area-lookups/data/areas/<snapshot>/areas.csv"
            )
        return cls({name: tuple(matches) for name, matches in by_name.items()})

    def resolve(self, name: str, region: str | None = None) -> list[AreaMatch]:
        matches = self._by_name.get(_key(name), ())
        if region is None:
            return list(matches)
        # A region that matches nothing narrows to empty rather than falling
        # back to every match: "Bilaspur in IN-MH" is a contradiction, and
        # answering it with the Chhattisgarh one would be a silent 1000km error.
        return [match for match in matches if match.region == region]
