"""Resolves place names against an area CSV held in memory.

The file is `src/dss/config/areas.csv` by default, generated by
`scripts/generate_area_csv.py` from an LGD snapshot — districts and blocks,
~7,900 rows, so the whole index is built once at startup and never re-read —
a lookup is a dict hit, not a file read, because it sits on the path of every
located turn.

Named `csv_lookup` rather than `csv` so the module does not shadow the stdlib
`csv` it imports.
"""

from __future__ import annotations

import csv
from bisect import bisect_left
from pathlib import Path

from dss.core.shared.models import Geometry
from dss.ports.area_lookup import AreaMatch


class AreaCsvUnusable(RuntimeError):
    """The area index could not be built, so no turn can resolve a place.

    Raised rather than logged: the file is checked in, so a missing or empty one
    means a broken build or a misconfigured path. Booting anyway would serve
    turns that have silently lost every spatial filter.
    """


def _key(name: str) -> str:
    """Case- and whitespace-insensitive. "  pune " and "Pune" are one key."""

    return " ".join(name.split()).lower()


class CsvAreaLookup:
    """An `AreaLookup` over a pre-built index. Use `load` to read a file."""

    def __init__(self, by_name: dict[str, tuple[AreaMatch, ...]]) -> None:
        self._by_name = by_name
        # Sorted once, at load: every key sharing a prefix sits in one
        # contiguous block, so `_qualified_by` finds where it starts with
        # `bisect_left` in O(log n) instead of scanning every key.
        self._sorted_keys = sorted(by_name)

    @classmethod
    def load(cls, path: Path) -> CsvAreaLookup:
        """Read the file once and hold the index. Raises `AreaCsvUnusable`
        if it cannot be read or carries no areas."""

        by_name: dict[str, list[AreaMatch]] = {}
        try:
            with path.open(newline="", encoding="utf-8") as handle:
                for row in csv.DictReader(handle):
                    match = AreaMatch(
                        name=row["area_name"],
                        region=row["region"],
                        # Coarsest first, e.g. "India;Maharashtra". `.get`
                        # rather than `[...]`, like `aliases` below: an index
                        # generated before the column existed is still
                        # readable, just with an empty chain.
                        within=tuple(
                            part
                            for part in (row.get("within") or "").split(";")
                            if part
                        ),
                        # GeoJSON order: longitude first.
                        geometry=Geometry(
                            coordinates=[
                                float(row["longitude"]),
                                float(row["latitude"]),
                            ]
                        ),
                    )
                    by_name.setdefault(_key(match.name), []).append(match)
                    # Aliases index to the same match, so "Bangalore" and
                    # "Bengaluru Urban" answer identically. `.get` rather than
                    # `[...]`: an index generated before the column existed is
                    # still readable, just without aliases.
                    for alias in (row.get("aliases") or "").split(";"):
                        if alias.strip():
                            by_name.setdefault(_key(alias), []).append(match)
        # KeyError and ValueError cover a renamed column and an unparseable
        # coordinate — both leave a partial index that would resolve some names
        # and silently miss others.
        except (OSError, KeyError, ValueError) as cause:
            raise AreaCsvUnusable(
                f"could not read the area index at {path}: {cause}. "
                f"Regenerate it with: uv run python scripts/generate_area_csv.py "
                f"--source <network-adapter>/tools/area-lookups/data/areas/"
                f"<snapshot>/areas.csv"
            ) from cause

        if not by_name:
            raise AreaCsvUnusable(
                f"the area index at {path} carries no areas, so no turn "
                f"could resolve a place name. Regenerate it with: uv run python "
                f"scripts/generate_area_csv.py --source <network-adapter>"
                f"/tools/area-lookups/data/areas/<snapshot>/areas.csv"
            )
        return cls({name: tuple(matches) for name, matches in by_name.items()})

    def country_codes(self) -> tuple[str, ...]:
        """The countries this file covers, as ISO 3166-1 codes ("IN" from
        "IN-MH")."""

        return tuple(
            sorted(
                {
                    match.region.partition("-")[0]
                    for matches in self._by_name.values()
                    for match in matches
                }
            )
        )

    def _qualified_by(self, wanted: str) -> tuple[AreaMatch, ...]:
        """Areas whose name begins with `wanted` as a whole word.

        "Bengaluru" names no district on its own; three qualify it (Urban,
        Rural, South). Whole-word, so "Pun" does not reach "Pune" — a partial
        word is a typo, and this must not turn one into a confident answer.

        Sorting puts every key sharing a prefix in one contiguous block:
        `bisect_left` finds where it starts in O(log n), then this walks
        forward only while `startswith` holds — no full scan of every key.
        """

        prefix = f"{wanted} "
        found: list[AreaMatch] = []
        start = bisect_left(self._sorted_keys, prefix)
        for key in self._sorted_keys[start:]:
            if not key.startswith(prefix):
                break
            found.extend(self._by_name[key])
        return tuple(found)

    async def resolve(self, name: str, region: str | None = None) -> list[AreaMatch]:
        # Async only to match the port. The index is in memory: nothing awaits.
        wanted = _key(name)
        # Exact first, and alone: "Mumbai" is a district *and* the start of
        # "Mumbai Suburban", so falling back here would turn a resolved name
        # into an ambiguous one.
        matches = self._by_name.get(wanted) or self._qualified_by(wanted)
        if region is None:
            return list(matches)
        # A region that matches nothing narrows to empty rather than falling
        # back to every match: "Bilaspur in IN-MH" is a contradiction, and
        # answering it with the Chhattisgarh one would be a silent 1000km error.
        return [match for match in matches if match.region == region]
